package com.example.showfadriverletest.common

import java.net.Socket

class Common {
    var Fullname = ""
    var Email = ""
    var Password = ""
    var MobileNo = ""
    var Gender = ""
    var Image = ""
    var DeviceType = ""
    var Token = ""
    var Lat = ""
    var Lng = ""
    var Status = ""
    var CreatedDate = ""
    var Id = ""

    companion object {
        //FOR SOCKET
        var socket: Socket? = null

        //FOR USER PREFERENCE
        var PREFRENCE_USER = "USER_DETAIL"
        var USER_PREFERENCE_KEY_ID = "id"
        var USER_PREFERENCE_KEY_FIRST_NAME = "firstName"
        var USER_PREFERENCE_KEY_LAST_NAME = "lastName"
        var USER_PREFERENCE_KEY_EMAIL = "email"
        var USER_PREFERENCE_KEY_IDENTIFY_NUMBER = "identify_umber"
        var USER_PREFERENCE_KEY_PASSWORD = "password"
        var USER_PREFERENCE_KEY_PHONE_NUMBER = "mobileno"
        var USER_PREFERENCE_KEY_GENDER = "gender"
        var USER_PREFERENCE_KEY_DATE_OF_BIRTH = "dob"
        var USER_PREFERENCE_KEY_IMAGE = "profileimage"
        var USER_PREFERENCE_KEY_DEVICE_TYPE = "deviceType"
        var USER_PREFERENCE_KEY_TOKEN = "deviceToken"
        var USER_PREFERENCE_KEY_LATITUDE = "latitude"
        var USER_PREFERENCE_KEY_LONGITUDE = "longitude"
        var USER_PREFERENCE_KEY_STATUS = "status"
        var USER_PREFERENCE_KEY_CREATED_DATE = "createdDate"
        var USER_PREFERENCE_USER_TYPE = "userType"
        var USER_PREFERENCE_COMPANY_ID = "company_id"
        var USER_PREFERENCE_COMAPNY_NAME = "company_name"
        var USER_PREFERENCE_KEY_WALLET_BALLENCE = "walletBalance" // wallet balance
        var USER_PREFERENCE_KEY_ADDRESS = "address"
        var USER_PREFERENCE_KEY_SOCIALID = "socialId"
        var USER_PREFERENCE_KEY_SOCIALTYPE = "socialType"
        var USER_PREFERENCE_KEY_X_API = "x_api_key"
        var USER_PREFERENCE_KEY_QR_CODE = "QRCode"
        var USER_PREFERENCE_KEY_REFERAL_CODE = "referralCode"
        var USER_PREFERENCE_KEY_MILE_BALANCE = "current_miles_balance"
        var USER_PREFERENCE_KEY_MILE_BALANCE_CORP = "current_miles_balance_CORP"
        var USER_PREFERENCE_KEY_PURCHASE_BALANCE = "total_miles_balance"
        var USER_PREFERENCE_KEY_PURCHASE_BALANCE_CORP = "total_miles_balance_corp"
        var USER_PREFERENCE_KEY_DEFAULT_TYRE = "paymentType"
        var USER_PREFERENCE_KEY_DEFAULT_CARD_ID = "cardId"
        var USER_PREFERENCE_KEY_DEFAULT_CARD_NAME = "cardName"
        var USER_PREFERENCE_KEY_DEFAULT_CARD_NUMBER = "cardNumber"
        var USER_PREFERENCE_KEY_DEFAULT_CARD_CVV = "cardCvv"
        var USER_PREFERENCE_KEY_CAR_CLASS = "carClass"
        var USER_PREFERENCE_KEY_CARD_LIST = "cardList"
        var USER_PREFERENCE_KEY_VERIFY_USER = "VerifyUser"
        var USER_PREFERENCE_KEY_TICK_PAY_SPLASH = "TickpaySplash"
        var USER_PREFERENCE_KEY_COMPANY_NAME = "CompanyName"
        var USER_PREFERENCE_KEY_ABN = "ABN"
        var USER_PREFERENCE_KEY_BANK_NAME = "BankName"
        var USER_PREFERENCE_KEY_BANK_ACCOUNT_NUMBER = "BankAccountNumber"
        var USER_PREFERENCE_KEY_BSB = "BSB"
        var USER_PREFERENCE_KEY_DESCRIPTION = "Description"
        var USER_PREFERENCE_KEY_LICENCE_IMAGE = "LicenceImage"
        var USER_PREFERENCE_KEY_REFERAL_TOTAL = "referalTotal"
        var USER_PREFERENCE_KEY_RATTING = "ratting"
        var USER_PREFERENCE_KEY_OTP = "OTP"
        var PREFRENCE_NOTIFICATION = "notificationType"
        var USER_PREFERENCE_KEY_FULL_NAME = "fullName"
        var USER_PREFERENCE_KEY_BOOKING_DETAIL = "bookingDetail"
        var USER_PREFERENCE_KEY_METER_DETAIL = "meterDetail"
        var USER_PREFERENCE_KEY_INVITE_MESSAGE = "invite_message"
        var USER_PREFERENCE_KEY_SOS_NUMBER = "sos_number"
        var USER_INIT_DETAIL = "initDetail"
        var USER_PREFERENCE_KEY_VEHICLELIST = "vehicaltypelist"
        var USER_PREFERENCE_KEY_TRIP_FLAG = "tripFlag"
        var USER_PREFERENCE_KEY_TRIP_STARTED = "trip_started"
        var USER_PREFERENCE_KEY_DRIVER_ID = "driverId"
        var USER_PREFERENCE_KEY_DRIVER_NAME = "driverName"
        var CREATED_PASSCODE = "CreatePasscode"
        var IS_PASSCODE_REQUIRED = "isPasscodeRequired"
        var USER_PREFERENCE_KEY_SELECTED_CAR = "selectedCar"
        var USER_PREFERENCE_KEY_FAVORITE_PICKUP_LOCATION = "pickupLocation"
        var USER_PREFERENCE_KEY_FAVORITE_PICKUP_LAT = "pickupLat"
        var USER_PREFERENCE_KEY_FAVORITE_PICKUP_LONG = "pickupLong"
        var USER_PREFERENCE_KEY_FAVORITE_DROPOFF_LOCATION = "dropoffLocation"
        var USER_PREFERENCE_KEY_FAVORITE_DROPOFF_LAT = "dropoffLat"
        var USER_PREFERENCE_KEY_FAVORITE_DROPOFF_LONG = "dropoffLong"
        var USER_PREFERENCE_KEY_PRE_LAT = "preLat"
        var USER_PREFERENCE_KEY_PRE_LONG = "preLong"
        var USER_PREFERENCE_KEY_NEW_LAT = "newLat"
        var USER_PREFERENCE_KEY_NEW_LONG = "newLong"
        var PARAM_LANGUAGE_SWAHILI = "swahili_message"
        var USER_DEVICE_ID = "1234567890"
        var USER_CHAT_ID = "user_chat_id"
        var USER_CHAT_NAME = "user_chat_name"

        // trip info
        var DRIVER_IMAGE = "driverimage"
        var BOOKINGID = "bookingid"

        // init info
        var SESSION_INIT_INFO = "initdata"
        var SESSION_ESTIMATED_FARE = "estimatedfare"

        // socket keys for meter
        var UPDATE_METER_BOOKING_STATUS = "update_meter_booking_status"
        var START_WAITING_TIME_FOR_METER = "start_waiting_time_for_meter"
        var END_WAITING_TIME_FOR_METER = "end_waiting_time_for_meter"
        var METER_COMPLETE_TRIP = "meter_complete_trip"
        var METER_START_TRIP = "meter_start_trip"
    }
}
